### PR TITLE
rename variables

### PR DESCRIPTION
**Pull request by kroggen**
These changes make the code more understandable

### CODE REVIEW

**Comment by kroggen** [comment]
I added an additional commit that decrease computation by pre-computing `weight[index * weight_row_stride]` and putting the result in `weight`

**Comment by kroggen** [comment]
There is both `mat_vec_kernel` and `vec_mat_kernel` functions

It would be better to have more meaningful names

**Comment by ankan-ban** [comment]
Thank you. Certainly more readable. I will merge this soon (if you can fix the conflicts).

**Comment by kroggen** [comment]
The conflicts were fixed

**Review by ankan-ban — APPROVED** [review]
Thanks. Looks good.

**Pull request merged**
